export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  deepseekApiKey: process.env.DEEPSEEK_API_KEY ?? "",
  deepseekModel: process.env.DEEPSEEK_MODEL ?? "deepseek-chat",
  deepseekTimeoutMs: process.env.DEEPSEEK_TIMEOUT_MS ?? "60000",
  turnstileSiteKey: process.env.TURNSTILE_SITE_KEY ?? "",
  turnstileSecretKey: process.env.TURNSTILE_SECRET_KEY ?? "",
  aiDailyBudgetCny: process.env.AI_DAILY_BUDGET_CNY ?? "30",
  aiRequestReservationCny: process.env.AI_REQUEST_RESERVATION_CNY ?? "0.10",
  deepseekCacheHitCnyPerMillion: process.env.DEEPSEEK_CACHE_HIT_CNY_PER_MILLION ?? "0.05",
  deepseekCacheMissCnyPerMillion: process.env.DEEPSEEK_CACHE_MISS_CNY_PER_MILLION ?? "2.20",
  deepseekOutputCnyPerMillion: process.env.DEEPSEEK_OUTPUT_CNY_PER_MILLION ?? "8.80",
  logHashSalt: process.env.LOG_HASH_SALT ?? "",
  trustProxy: process.env.TRUST_PROXY === "true",
};
